spring.application.name=statusApp
spring.data.mongodb.uri=mongodb+srv://swagatikam1964:statusApp123@status-app.wnocd.mongodb.net/?retryWrites=true&w=majority&appName=status-app
spring.data.mongodb.database=statusApp
