spring.application.name=status-app
spring.data.mongodb.uri=mongodb+srv://swagatikam1964:statusApp123@status-app.wnocd.mongodb.net/?retryWrites=true&w=majority&appName=status-app
spring.data.mongodb.database=statusApp

logging.level.root=INFO
logging.level.com.example=DEBUG